version: '3.8'
services:
  mongodb:
    build: ./mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=Thoth

  server:
    build: ./server
    expose:
      - 8080
    environment:
      API_HOST: http://localhost:3000/
      APP_SERVER_PORT: 8080
    ports:
      - 8080:8080
    volumes:
      - ./server:/app/software_mil-server
    command: npm run start

  client:
    build: ./client
    environment:
      - REACT_APP_PORT=4000
    expose:
      - 4000
    ports:
      - 4000:4000
    volumes:
      - ./client/src:/app/software_mil-client/src
      - ./client/public:/app/software_mil-client/public
    links:
      - server
    command: npm run start
