version: "3.9"
services:
  mongodb:
    build: ./mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=Thoth
  server:
    build: ./server
    ports:
      - 6969:6969
  client:
    build: ./client
    ports:
      - 3000:3000
